# Generated by Django 3.2.17 on 2023-02-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='special_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
