# Generated by Django 3.2.17 on 2023-02-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_special_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='next_day',
            field=models.BooleanField(default=False),
        ),
    ]
