# Generated by Django 3.2.17 on 2023-04-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('epf_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
