# Generated by Django 3.2.17 on 2023-05-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20230429_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
