# Generated by Django 3.2.17 on 2023-02-21 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alllowance',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='salaryadvance',
            name='date_time',
        ),
        migrations.AddField(
            model_name='alllowance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 21, 9, 21, 43, 849322)),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 21, 9, 21, 43, 848327)),
        ),
    ]
