# Generated by Django 3.2.17 on 2023-02-21 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20230221_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alllowance',
            old_name='remark',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='alllowance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 21, 19, 40, 36, 18950)),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 21, 19, 40, 36, 18950)),
        ),
    ]
