# Generated by Django 3.2.17 on 2023-02-21 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20230221_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alllowance',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='alllowance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 21, 21, 51, 24, 767614)),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 21, 21, 51, 24, 766617)),
        ),
    ]
