# Generated by Django 3.2.17 on 2023-04-04 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_auto_20230404_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllowance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 4, 12, 9, 43, 450165)),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 4, 12, 9, 43, 449162)),
        ),
    ]
