# Generated by Django 3.2.17 on 2023-05-16 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0040_auto_20230429_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllowance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 16, 9, 13, 37, 127256)),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 16, 9, 13, 37, 127256)),
        ),
    ]
