# Generated by Django 3.2.17 on 2023-05-26 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0041_auto_20230516_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllowance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 26, 21, 28, 48, 954955)),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 26, 21, 28, 48, 953940)),
        ),
    ]
