# Generated by Django 3.2.17 on 2023-06-05 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0042_auto_20230526_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllowance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 14, 40, 9, 482245)),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 14, 40, 9, 482245)),
        ),
    ]
