# Generated by Django 3.2.17 on 2023-06-08 02:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_auto_20230605_1440'),
        ('payroll', '0043_auto_20230605_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllowance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 8, 8, 9, 34, 63672)),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 8, 8, 9, 34, 63672)),
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 6, 8, 8, 9, 34, 63672))),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('time_stamp', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
