# Generated by Django 3.2.17 on 2023-06-29 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0044_auto_20230608_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllowance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 15, 18, 5, 88349)),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 15, 18, 5, 88349)),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 15, 18, 5, 87350)),
        ),
    ]
