# Generated by Django 3.2.17 on 2023-07-24 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0048_auto_20230629_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllowance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 12, 53, 0, 346860)),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 12, 53, 0, 346860)),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 12, 53, 0, 346860)),
        ),
    ]
