# Generated by Django 3.2.17 on 2023-10-15 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0050_auto_20231015_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllowance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 18, 50, 3, 882621)),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 18, 50, 3, 882621)),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 18, 50, 3, 882621)),
        ),
    ]
