# Generated by Django 4.1.5 on 2023-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('epf_no', models.CharField(max_length=10)),
                ('appoinment_date', models.DateField()),
                ('date_of_termination', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_account_no', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
    ]
