# Generated by Django 4.1.5 on 2023-01-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_nic_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_acc_name',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
