# Generated by Django 3.2.17 on 2023-02-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_bank_acc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
