# Generated by Django 3.2.17 on 2023-02-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_acc_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nic_no',
            field=models.CharField(max_length=15),
        ),
    ]
