# Generated by Django 3.2.17 on 2023-02-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
    ]
