# Generated by Django 3.2.17 on 2023-02-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(max_length=60),
        ),
    ]
