# Generated by Django 3.2.17 on 2023-03-17 10:47

from django.db import migrations, models
import django.db.models.deletion
def set_default_bank(apps, schema_editor):
    Employee = apps.get_model('employee', 'Employee')
    Bank = apps.get_model('employee', 'Bank')
    default_bank = Bank.objects.first()
    Employee.objects.update(bank=default_bank)

class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_bank_bankbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.bank'),
        ),
        migrations.RunPython(set_default_bank),
    ]
