# Generated by Django 3.2.17 on 2023-10-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthsummary',
            name='total_etf',
        ),
    ]
