# Generated by Django 3.2.17 on 2024-01-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_monthsummary_total_etf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthsummary',
            name='total_allowance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthsummary',
            name='total_epf',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthsummary',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthsummary',
            name='total_salary_advance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
