# Generated by Django 3.2.17 on 2023-02-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emp_type', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('epf_no', models.CharField(max_length=10)),
                ('nic_no', models.CharField(max_length=15)),
                ('appoinment_date', models.DateField()),
                ('termination_date', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(max_length=20)),
                ('bank_acc_name', models.CharField(max_length=20)),
                ('bank_acc_no', models.CharField(max_length=15)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
    ]
