# Generated by Django 3.2.17 on 2023-02-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_payment', models.FloatField()),
                ('ot_payment_rate', models.FloatField()),
                ('fixed_allowance', models.FloatField()),
                ('leave_payment', models.FloatField()),
                ('br_payment', models.FloatField()),
                ('epf', models.FloatField()),
                ('advance_limit', models.FloatField()),
                ('room_charge', models.FloatField()),
                ('staff_welf_contribution', models.FloatField()),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
