# Generated by Django 3.2.17 on 2023-02-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeefinance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefinance',
            name='submit_date',
            field=models.DateTimeField(),
        ),
    ]
