# Generated by Django 3.2.17 on 2023-02-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employeefinance_advance_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='appoinment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(null=True),
        ),
    ]
