# Generated by Django 3.2.17 on 2023-02-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employeefinance_fixed_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
