# Generated by Django 3.2.17 on 2023-02-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefinance',
            name='epf_type',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
