# Generated by Django 3.2.17 on 2023-02-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employeefinance_epf_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_type',
        ),
    ]
