# Generated by Django 3.2.17 on 2023-03-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employeefinance_basic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_type',
            field=models.IntegerField(default=0),
        ),
    ]
