# Generated by Django 3.2.17 on 2023-03-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_employee_emp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefinance',
            name='daily_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employeefinance',
            name='ot_payment_rate',
            field=models.FloatField(default=0),
        ),
    ]
