# Generated by Django 3.2.17 on 2023-04-06 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_alter_bank_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.bank'),
        ),
    ]
