# Generated by Django 3.2.17 on 2023-04-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_employee_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active_status',
            field=models.IntegerField(default=1),
        ),
    ]
