# Generated by Django 3.2.17 on 2023-06-05 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_employee_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefinance',
            name='effective_from',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
        migrations.AddField(
            model_name='employeefinance',
            name='reason',
            field=models.CharField(default='', max_length=100),
        ),
    ]
