# Generated by Django 3.2.17 on 2023-06-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_auto_20230605_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefinance',
            name='morning_shift',
            field=models.BooleanField(default=False),
        ),
    ]
