# Generated by Django 3.2.17 on 2023-06-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_employeefinance_morning_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefinance',
            name='morning_shift',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
