# Generated by Django 3.2.17 on 2023-06-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_alter_employeefinance_morning_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeefinance',
            old_name='morning_shift',
            new_name='morning_ot',
        ),
    ]
