# Generated by Django 3.2.17 on 2023-06-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_rename_morning_shift_employeefinance_morning_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefinance',
            name='morning_ot',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
